### ISSUE TITLE
Error while running the evaluate policy

### ISSUE THREAD

**Issue by coder-rakeshpaul** [microsoft/MoCapAct#16]
Hi I ran the evaluate policy as mentioned
`python mocapact/clip_expert/evaluate.py --policy_root data/experts/CMU_009_12-165-363/eval_rsi/model --always_init_at_clip_start --device cpu --ghost_offset 1 --act_noise 0
`
This throws an error as

`ialization.py", line 1025, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported class numpy.core.multiarray.scalar
`

I also Tried the python scripts

```
from mocapact import observables
from mocapact.sb3 import utils

expert_path = 'data/experts/CMU_009_12-165-363/eval_rsi/model'
expert = utils.load_policy(expert_path, observables.TIME_INDEX_OBSERVABLES)


from mocapact.envs import tracking
from dm_control.locomotion.tasks.reference_pose import types
dataset = types.ClipCollection(ids=['CMU_009_12'], start_steps=[165], end_steps=[363])
env = tracking.MocapTrackingGymEnv(dataset)
obs, done = env.reset(), False
while not done:
    action, _ = expert.predict(obs, deterministic=True)
    obs, rew, done, _ = env.step(action)
    print(rew)
```

Still gave that error
![image](https://github.com/microsoft/MoCapAct/assets/114281050/e4850804-3095-46c9-8c0e-fa3d42ad1b56)

What might be the cause of this?

edit: I tried setting the weights_only to false and tried running it again. It still showed some error, this time regarding gym. My guess is that since gym is deprecated and the developers have shifted to gymnasium we should also be doing the same. Not sure how to accomplish that though, any idea or suggestions on what might be done now ??

edit 2: Okay I managed to run gym also but When trying to visualize the expert it's throwing errors to open a window

`python mocapact/clip_expert/evaluate.py --act_noise 0. --visualize --termination_error_threshold 1000000 --ghost_offset 1 --always_init_at_clip_start --policy_root data/experts/CMU_009_12-0-198/eval_rsi/model

`
I used the above one to try and visualize, and it gave me an error like
![image](https://github.com/microsoft/MoCapAct/assets/114281050/aa6af6a8-db92-441c-94c6-350b9d89046a)

When trying the above API of python it just prints the numbers and no window of visualizing is opened

Thank you

**Comment by nolanwagener** [comment]
Hi Rakesh, have you followed these instructions to get rendering working for dm_control? https://github.com/google-deepmind/dm_control?tab=readme-ov-file#rendering

**Comment by coder-rakeshpaul** [comment]
Hi @nolanwagener thanks for the reply. yes I tried that doesn't seem to work still. Not sure what the issue is. At any rate I don't think this is currently the issue with this repo. I'll try posting it on dm_control and check what their response is.

I do have few questions regarding the use of gym in this repo. Do you think we can maybe use gymnasium in place of gym. (since the have stopped support for gym and migrated to gymnasium and even stable_baselines3 have moved to it)?

**Comment by coder-rakeshpaul** [comment]
I figured this out turns out it was some issue with glfw on linux and not some issue with dm_control or mocapact. One can try out the instructions in dm_control and if still facing difficulty with glfw can refer to [this](https://stackoverflow.com/questions/72110384/libgl-error-mesa-loader-failed-to-open-iris)
